#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldcaret.ls -> dist/ldcaret.js ..."
./node_modules/.bin/lsc -cbp src/ldcaret.ls > dist/ldcaret.js
echo "minifying ldcaret.js ..."
./node_modules/.bin/uglifyjs dist/ldcaret.js > dist/ldcaret.min.js
echo "deploy into local web ..."
rm -rf web/static/assets/lib/ldcaret/dev/
mkdir -p web/static/assets/lib/ldcaret/dev/
cp -R dist/* web/static/assets/lib/ldcaret/dev/
echo "done."

