#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldcaret.ls -> dist/ldcaret.js ..."
./node_modules/.bin/lsc -cbp src/ldcaret.ls > dist/ldcaret.js
echo "minifying ldcaret.js ..."
./node_modules/.bin/uglifyjs dist/ldcaret.js > dist/ldcaret.min.js
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/
cp -R dist/* web/static/assets/lib/
echo "done."

