#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cbp src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "deploy into local web ..."
rm -rf web/static/assets/lib/ldcaret/dev/
mkdir -p web/static/assets/lib/ldcaret/dev/
cp -R dist/* web/static/assets/lib/ldcaret/dev/
echo "done."

